server:
  port: 9527

spring:
  application:
    name: tn-bos-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept  单个可用
  prefix: /tunan   #代理一个统一的公共前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: tn-bos-login
    mydept.path: /mylogin/**


info:
  app.name: TN-BOS
  company.name: www.tunan.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$